#!/usr/bin/env python3
from pathlib import Path
import json, html
ROOT=Path(__file__).resolve().parents[1]; DATA=ROOT/'data'; SITE=ROOT/'site'; BASE='/dc-public-realm'
def load(n): return json.loads((DATA/n).read_text(encoding='utf-8'))
def esc(x): return html.escape(str(x))
S={x['source_id']:x for x in load('sources.json')['sources']}
def link(sid,label=None):
 s=S[sid]; return f'<a href="{esc(s["url"])}">{esc(label or s["title"])}</a>'
css='''<style>:root{--fg:#171717;--muted:#606060;--line:#d9d9d4;--soft:#f7f7f3;--accent:#5a3d16}*{box-sizing:border-box}body{margin:0;color:var(--fg);font-family:ui-serif,Georgia,serif;line-height:1.62}header,main,footer{max-width:900px;margin:auto;padding:1.2rem}header{border-bottom:1px solid var(--line)}h1{font-size:clamp(2.4rem,7vw,4.6rem);line-height:1.05}h2{margin-top:3rem;border-bottom:1px solid var(--line);padding-bottom:.35rem}.lede{font-size:1.2rem;max-width:760px}.small,.eyebrow{font-family:ui-sans-serif,system-ui,sans-serif;color:var(--muted);font-size:.88rem}.eyebrow{letter-spacing:.06em}.card{border:1px solid var(--line);padding:1rem;margin:1rem 0}.question{border-left:4px solid var(--accent);padding:1rem;background:#fffdf8;margin:1rem 0}.choice{display:inline-block;border:1px solid var(--line);padding:.35rem .55rem;margin:.2rem .25rem .2rem 0;font-family:ui-sans-serif,system-ui,sans-serif;font-size:.88rem}.compare{width:100%;border-collapse:collapse}.compare th,.compare td{border-bottom:1px solid var(--line);padding:.75rem;vertical-align:top;text-align:left}.compare th{font-family:ui-sans-serif,system-ui,sans-serif;font-size:.85rem}a{color:inherit}footer{border-top:1px solid var(--line);margin-top:3rem;color:var(--muted)}</style>'''
body=f'''<div class="eyebrow">SCHOLARLY REVIEW · OBJ-0001</div><h1>Artigas memorial: review brief</h1><p class="lede">This page is a focused request for professional art-historical review of one object. The project is testing whether claim-level evidence and source genealogy can preserve uncertainty better than a conventional catalog record without making the public interface harder to use.</p><p><a href="{BASE}/objects/jose-gervasio-artigas/">View the public object page</a></p>
<section><h2>What we are asking reviewers to test</h2><p>We are not asking for endorsement of the database. We are asking where its decomposition of the Artigas record is useful, misleading, incomplete, or incompatible with professional art-historical practice.</p><div class="card"><strong>Core question</strong><p>Does separating object history into claim-level propositions—each with explicit evidence, uncertainty, and source ancestry—clarify the scholarship, or does it fragment judgments that should remain contextual and narrative?</p></div></section>
<section><h2>Where our record differs from the Smithsonian presentation</h2><table class="compare"><tr><th>Issue</th><th>Current project treatment</th><th>Review question</th></tr>
<tr><td>Authorship / creative roles</td><td>Separates Juan Luis Blanes's commission, Juan Manuel Blanes's development of the <em>boceto</em>, and Dante Costa's modeling/casting role, based principally on {link('SRC-UY-003','Uruguay Resolution 732/004')}.</td><td>Is this decomposition art-historically useful, or does it over-formalize a creative sequence better handled narratively?</td></tr>
<tr><td>Predecessor object</td><td>The Uruguayan heritage record identifies Washington among bronzes copying the 1898 San José monument. The {link('SRC-US-004','Smithsonian inventory')} instead describes a recast while locating the predecessor in Montevideo. We publish this as a conflict rather than normalize it.</td><td>How should a museum catalog distinguish object identity, prototype, recast, replica, and derivative copy here?</td></tr>
<tr><td>Washington caster/foundry</td><td>The Smithsonian founder field is treated as “not identified by this source,” not proof that the founder is historically unknown.</td><td>Is that distinction consistent with cataloging and provenance practice?</td></tr>
<tr><td>Early-1940s recast date</td><td>Retained as a Smithsonian-attributed historical claim while its documentary ancestry remains unresolved.</td><td>What level of qualification would a professional catalog normally apply before repeating this chronology?</td></tr></table></section>
<section><h2>What is comparatively well documented</h2><p>The gift/acceptance chain has direct U.S. congressional evidence in {link('SRC-US-001','Senate Report 1439 / S.2591')}. Current custody has an administrative record. The San José creative sequence has a later official Uruguayan heritage record that names underlying 1894 and 1896 acts, which are now targeted for retrieval rather than treated as permanently sufficient substitutes for the originals.</p></section>
<section><h2>What remains unresolved</h2>
<div class="question"><strong>Claim ancestry inside the Smithsonian record</strong><p>The public Smithsonian inventory cites Goode (1974), NPS (1985), Michael Richman's 1967–69 work, and a 1991 Smithsonian research project, but it does not map individual Artigas claims to those research streams.</p><p><a href="https://github.com/danielastone/dc-public-realm/issues/19">Goode</a> · <a href="https://github.com/danielastone/dc-public-realm/issues/20">Richman</a> · <a href="https://github.com/danielastone/dc-public-realm/issues/21">NPS 1985</a> · <a href="https://github.com/danielastone/dc-public-realm/issues/22">Smithsonian 1991</a></p></div>
<div class="question"><strong>Washington fabrication history</strong><p>The foundry, exact casting process, and documentary basis for the early-1940s date have not yet been traced to a contemporary fabrication or diplomatic record.</p></div>
</section>
<section><h2>Useful forms of reviewer response</h2><p>A response does not need to address the whole project. Any one of these is useful:</p><span class="choice">Confirm a distinction</span><span class="choice">Correct a claim</span><span class="choice">Add a source</span><span class="choice">Flag an interpretive issue</span><span class="choice">Suggest another curator/archive</span><span class="choice">Mark something unresolved</span><p class="small">The project will preserve reviewer-supplied evidence as a new research input; it will not silently overwrite an existing claim or convert institutional agreement into automatic corroboration.</p></section>
<section><h2>Methodological boundary</h2><p>The project separates three kinds of proposition: <strong>Historical record</strong>, <strong>Attribution</strong>, and <strong>Interpretation</strong>. The first two are already used on the Artigas page. Interpretation is deliberately guarded so that repeated publication cannot mechanically turn an interpretive argument into “verified fact.”</p></section>'''
page=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Artigas scholarly review brief</title>{css}</head><body><header><a href="{BASE}/">Diplomatic Gifts in Washington</a></header><main>{body}</main><footer>Focused scholarly review page for the Artigas vertical slice. This page does not alter claim status.</footer></body></html>'''
out=SITE/'review'/'artigas'/'index.html'; out.parent.mkdir(parents=True,exist_ok=True); out.write_text(page,encoding='utf-8'); print('Wrote',out)
