#!/usr/bin/env python3
from pathlib import Path
import json, html
ROOT=Path(__file__).resolve().parents[1]; DATA=ROOT/'data'; SITE=ROOT/'site'; BASE='/dc-public-realm'
def load(n): return json.loads((DATA/n).read_text(encoding='utf-8'))
def esc(x): return html.escape(str(x))
S={x['source_id']:x for x in load('sources.json')['sources']}
def link(sid,label=None):
 s=S[sid]; return f'<a href="{esc(s["url"])}">{esc(label or s["title"])}</a>'
body=f'''<div class="eyebrow">PROFESSIONAL REVIEW · OBJ-0001</div><h1>Artigas Memorial Review Brief</h1><p class="lede">This brief identifies four points in the José Gervasio Artigas Memorial record that require art-historical or cataloging review.</p><p><a href="{BASE}/objects/jose-gervasio-artigas/">Public object record</a> · <a href="{BASE}/collaborate/artigas/">Open research tasks</a></p>
<section><h2>Review requested</h2><p>Please review any of the issues below. A response may address one issue only. Useful responses include a correction, source citation, cataloging distinction, archival reference, or referral to another collection or specialist.</p></section>
<section><h2>Issues for review</h2><table class="compare"><tr><th>Issue</th><th>Current record</th><th>Requested review</th></tr>
<tr><td>Creative roles</td><td>{link('SRC-UY-003','Uruguay Resolution 732/004')} records separate roles for Juan Luis Blanes, Juan Manuel Blanes, and Dante Costa in the San José monument.</td><td>Does the current separation of commission, design development, modeling, and casting accurately represent the documented roles?</td></tr>
<tr><td>Predecessor object</td><td>The Uruguayan heritage record identifies the Washington bronze as a copy of the 1898 San José monument. The {link('SRC-US-004','Smithsonian inventory')} describes a recast and places the predecessor in Montevideo.</td><td>How should the record distinguish the predecessor object and the terms copy, recast, replica, or derivative work?</td></tr>
<tr><td>Washington caster or foundry</td><td>The sources reviewed do not identify the foundry or caster of the Washington bronze.</td><td>Does the Smithsonian record or related research documentation identify a founder, caster, or fabrication source?</td></tr>
<tr><td>Recast date</td><td>The Smithsonian inventory dates the recast to approximately the early 1940s. The documentary source for that date has not been identified.</td><td>What source supports the date, and how should it be qualified pending recovery of that source?</td></tr></table></section>
<section><h2>Established records</h2><p>{link('SRC-US-001','Senate Report 1439 / S.2591')} documents the U.S. gift and acceptance process. A current administrative record identifies custody. Uruguay Resolution 732/004 records the creative sequence for the San José monument and cites earlier 1894 and 1896 acts that remain targets for retrieval.</p></section>
<section><h2>Source records requested</h2><div class="question"><strong>Smithsonian source history</strong><p>The public Smithsonian inventory cites Goode (1974), National Park Service material (1985), Michael Richman's 1967–69 research, and a 1991 Smithsonian research project. It does not assign those sources to individual statements in the Artigas record.</p><p><a href="https://github.com/danielastone/dc-public-realm/issues/19">Goode task</a> · <a href="https://github.com/danielastone/dc-public-realm/issues/20">Richman task</a> · <a href="https://github.com/danielastone/dc-public-realm/issues/21">NPS task</a> · <a href="https://github.com/danielastone/dc-public-realm/issues/22">1991 Smithsonian task</a></p></div><div class="question"><strong>Washington fabrication records</strong><p>Records identifying the foundry, casting process, or contemporary basis for the early-1940s date have not been located.</p></div></section>
<section><h2>How review affects the record</h2><p>Reviewer comments are treated as research input. A factual correction changes the public record only after the supporting source is identified and reviewed. When reliable sources disagree, the disagreement remains documented.</p></section>'''
page=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Artigas professional review brief</title><link rel="stylesheet" href="{BASE}/assets/style.css"></head><body class="page-review"><header><a href="{BASE}/">Diplomatic Gifts in Washington</a></header><main>{body}</main><footer>Professional review brief. Comments do not change the catalog record until supporting evidence is reviewed.</footer></body></html>'''
out=SITE/'review'/'artigas'/'index.html'; out.parent.mkdir(parents=True,exist_ok=True); out.write_text(page,encoding='utf-8'); print('Wrote',out)
