#!/usr/bin/env python3
from __future__ import annotations
import html,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; DATA=ROOT/'data'; SITE=ROOT/'site'; BASE='/dc-public-realm'
def load(n): return json.loads((DATA/n).read_text(encoding='utf-8'))
def esc(x): return html.escape(str(x))
E={x['entity_id']:x for x in load('entities.json')['entities']}; A={x['assertion_id']:x for x in load('assertions.json')['assertions']}; S={x['source_id']:x for x in load('sources.json')['sources']}; evidence=load('assertion-evidence.json')['assertion_evidence']; tasks=[x for x in load('research-tasks.json')['tasks'] if x.get('object_entity_id')=='OBJ-0001']; EV={}
for e in evidence: EV.setdefault(e['assertion_id'],[]).append(e)
ROLE={'PRIMARY_SUPPORT':'Main source','CORROBORATION':'Additional source','QUALIFIES':'Qualification','CONTRADICTS':'Contradictory source','IMAGE_EVIDENCE':'Image evidence'}
CLAIMS=[('A-0001','Gift to the United States','Congressional records describe the memorial as a gift from the people of Uruguay.'),('A-0002','Current custody','The National Park Service is recorded as the current custodian.'),('A-0004','Relationship to the earlier monument','Uruguay’s heritage record identifies the Washington bronze as a copy of the 1898 Artigas monument at San José de Mayo. A Smithsonian inventory instead calls the Washington work a recast while locating its predecessor in Montevideo, so the exact physical-object relationship remains contested.'),('A-0005','Casting location','A Smithsonian inventory associates the Washington recast with Montevideo, Uruguay. The present evidence does not establish the foundry.'),('A-0005B','Approximate recast date','The Smithsonian inventory dates the Washington recast approximately to the early 1940s.')]
def slink(s): return f'<a href="{esc(s["url"])}">{esc(s["title"])}</a>'
def evidence_label(evs):
 pubs={e.get('source_id') for e in evs if e.get('source_id')}; n=len(pubs)
 if any(e.get('evidence_role')=='CONTRADICTS' for e in evs): return f'{n} publications · sources conflict'
 pos=[e for e in evs if e.get('evidence_role') in {'PRIMARY_SUPPORT','CORROBORATION','IMAGE_EVIDENCE'}]
 if len(pos)>1 and any(e.get('claim_origin')=='UNKNOWN' for e in pos): return f'{n} publications · claim ancestry partly unresolved'
 return f'{n} publication'+('s' if n!=1 else '')
def epanel(aid):
 rows=[]
 for e in EV.get(aid,[]):
  s=S[e['source_id']]; note=e.get('evidence_note',''); rows.append(f'<div class="source-row"><strong>{esc(ROLE.get(e["evidence_role"],e["evidence_role"]))}</strong> · {slink(s)}<div class="small">{esc(e.get("locator","Record"))}{" — "+esc(note) if note else ""}</div></div>')
 return f'<details class="evidence"><summary>Evidence for this claim <span>{esc(evidence_label(EV.get(aid,[])))}</span></summary>{"".join(rows)}<p class="small"><a href="#provenance-{esc(aid)}">View technical provenance</a></p></details>'
def claim(aid,title,text): return f'<article class="claim"><h3>{esc(title)}</h3><p>{esc(text)} <a class="cite" href="#provenance-{esc(aid)}">[{esc(aid.replace("A-",""))}]</a></p>{epanel(aid)}</article>'
def question(t): return f'<article class="question"><div class="eyebrow">OPEN RESEARCH QUESTION</div><h3>{esc(t["title"])}</h3><p>{esc(t["research_gap"])}</p><p><strong>What would help:</strong> {esc(t["high_value_result"])}</p><a class="button" href="{BASE}/tasks/{esc(t["task_id"].lower())}/">Help with this research</a><details><summary>Research requirements</summary><p class="small">{esc(t["critical_rule"])}</p></details></article>'
def prov(aid):
 a=A[aid]; rows=[]
 for e in EV.get(aid,[]):
  s=S[e['source_id']]; inh=', '.join(e.get('inherits_claim_from_source_ids',[])) or 'none recorded'; rows.append(f'<li><strong>{esc(e["source_id"])}</strong> — {esc(s["title"])}<br><span class="small">role={esc(e["evidence_role"])} · authority_fit={esc(e.get("authority_fit"))} · proximity={esc(e.get("proximity"))} · claim_origin={esc(e.get("claim_origin"))} · inherited_from={esc(inh)}</span></li>')
 return f'<details class="technical" id="provenance-{esc(aid)}"><summary>{esc(aid)} · {esc(a["predicate"])}</summary><ul>{"".join(rows)}</ul></details>'
roles=[]
for aid,label in [('A-0007A','Commission entrusted to'),('A-0007B','Sketch developed by'),('A-0007C','Modeled and cast by')]:
 obj=E.get(A[aid].get('object_entity_id'),{}).get('canonical_name','Unresolved'); roles.append(f'<li><strong>{esc(label)}:</strong> {esc(obj)}{epanel(aid)}</li>')
sids=[]
for aid in [x[0] for x in CLAIMS]+['A-0007A','A-0007B','A-0007C']:
 for e in EV.get(aid,[]):
  if e['source_id'] not in sids: sids.append(e['source_id'])
source_cards=''.join(f'<li>{slink(S[sid])}<br><span class="small">{esc(S[sid].get("publisher_or_creator",""))} · {esc(S[sid].get("authority_scope",""))}</span></li>' for sid in sids)
css='''<style>:root{--fg:#171717;--muted:#606060;--line:#d9d9d4;--soft:#f7f7f3;--accent:#5a3d16}*{box-sizing:border-box}body{margin:0;color:var(--fg);font-family:ui-serif,Georgia,serif;line-height:1.62}header,main,footer{max-width:900px;margin:auto;padding:1.2rem}header{border-bottom:1px solid var(--line)}nav a{margin-right:1rem;color:inherit}.eyebrow,.small,summary span{font-family:ui-sans-serif,system-ui,sans-serif;color:var(--muted);font-size:.86rem}.eyebrow{letter-spacing:.06em}h1{font-size:clamp(2.3rem,7vw,4.7rem);line-height:1;margin:.3rem 0 1rem}h2{margin-top:3rem;border-bottom:1px solid var(--line);padding-bottom:.35rem}.lede{font-size:1.25rem;max-width:760px}.claim,.question{margin:1.4rem 0}.claim h3,.question h3{margin-bottom:.25rem}.cite{text-decoration:none;font-family:ui-sans-serif,system-ui,sans-serif;font-size:.75rem;vertical-align:super}.evidence,.technical{background:var(--soft);border:1px solid var(--line);padding:.65rem .8rem;margin:.6rem 0}.evidence summary,.technical summary{cursor:pointer;font-family:ui-sans-serif,system-ui,sans-serif;font-weight:650}.evidence summary span{float:right;font-weight:400}.source-row{padding:.6rem 0;border-top:1px solid var(--line)}.source-row:first-of-type{margin-top:.5rem}.question{border-left:4px solid var(--accent);padding:1rem;background:#fffdf8}.button{display:inline-block;border:1px solid var(--fg);padding:.45rem .75rem;color:inherit;text-decoration:none}.tabs{position:sticky;top:0;background:white;border-bottom:1px solid var(--line);padding:.7rem 0;z-index:2}.tabs a{margin-right:1rem;font-family:ui-sans-serif,system-ui,sans-serif;font-size:.9rem;color:inherit}.sources li,.technical li{margin:.7rem 0}footer{border-top:1px solid var(--line);margin-top:3rem;color:var(--muted)}@media(max-width:600px){.evidence summary span{float:none;display:block;margin-top:.2rem}.tabs{position:static}}</style>'''
body=f'''<div class="eyebrow">OBJ-0001 · URUGUAY · PUBLICATION PROTOTYPE</div><h1>José Gervasio Artigas Memorial</h1><p class="lede">A diplomatic monument in Washington, D.C., connected to an earlier Artigas monument in San José de Mayo, Uruguay. This page separates what the records document from what later catalogs attribute or leave unresolved.</p><nav class="tabs"><a href="#overview">Overview</a><a href="#evidence">Evidence</a><a href="#sources">Sources</a><a href="#questions">Open questions</a><a href="#provenance">Provenance</a></nav><section id="overview"><h2>Overview</h2><p>U.S. congressional records describe the memorial as a gift from the people of Uruguay. The National Park Service is recorded as its current custodian. Uruguay’s heritage record identifies the Washington bronze as a copy of the 1898 Artigas monument at San José de Mayo; a Smithsonian inventory describes a recast but places the predecessor in Montevideo. The exact physical-object relationship is therefore published as contested rather than normalized away.</p><p>The creative history of the San José monument is more complicated than a single “sculptor” field suggests. Uruguay's heritage resolution records a sequence involving Juan Luis Blanes, Juan Manuel Blanes, and Dante Costa:</p><ul>{''.join(roles)}</ul><p class="small">The evidence currently available for the Washington casting does not identify a foundry. A source failing to identify the founder is not treated as proof that the founder is historically unknowable.</p></section><section id="evidence"><h2>Evidence</h2><p>Claims are presented in ordinary language first. Open an evidence panel to see supporting, qualifying, and contradictory publications and whether their claim ancestry has been established.</p>{''.join(claim(*x) for x in CLAIMS)}</section><section id="sources"><h2>Sources</h2><p>These are sources actually connected to claims on this page. An external institutional record is not automatically evidence for every proposition about the monument.</p><ul class="sources">{source_cards}</ul></section><section id="questions"><h2>Open questions</h2><p>These are bounded research problems. Finding a source does not change the knowledge graph until the underlying material is reviewed.</p>{''.join(question(t) for t in tasks)}</section><section id="provenance"><h2>Technical provenance</h2><p>This optional layer exposes internal claim and source-lineage metadata used to prevent multiple publications from being mistaken for independent corroboration.</p>{''.join(prov(aid) for aid in [x[0] for x in CLAIMS]+['A-0007A','A-0007B','A-0007C'])}</section>'''
page=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>José Gervasio Artigas Memorial | Diplomatic Gifts in Washington</title>{css}</head><body><header><div class="eyebrow">Diplomatic Gifts in Washington · alpha</div><nav><a href="{BASE}/">Home</a><a href="{BASE}/methodology/">Methodology</a><a href="{BASE}/collaborate/">Collaborate</a></nav></header><main>{body}</main><footer>Public presentation is derived from the research graph. Open research leads do not affect claim status until reviewed.</footer></body></html>'''
out=SITE/'objects'/'jose-gervasio-artigas'/'index.html'; out.parent.mkdir(parents=True,exist_ok=True); out.write_text(page,encoding='utf-8'); print('Wrote',out)
